//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Deatils
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddr { get; set; }
        public int EmpPhone { get; set; }
        public string EmpEmail { get; set; }
        public string EmpGender { get; set; }
        public string EmpDesignation { get; set; }
        public string EmpPassword { get; set; }
    }
}
