//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Login
    {
        public int ID { get; set; }
        public string Login_ID { get; set; }
        public string EmpName { get; set; }
        public string EmpAddress { get; set; }
        public int EmpPhone { get; set; }
        public string EmpEmail { get; set; }
        public string EmpGender { get; set; }
        public string EmpDesignation { get; set; }
        public string Password { get; set; }
    }
}
